### ISSUE TITLE
Tópico <1>

### ISSUE THREAD

**Issue by santos-bruna** [plinioleitao/bd-2021-2-bec#110]
<Meu registro acadêmico: 201905483.
  Meu repositório no Github: https://github.com/santos-bruna/bd-2021-2-bec.>

**Comment by plinioleitao** [comment]
Prefira o título 'Tópico 01', em vez de 'Tópico <1>'.
O endereço do seu repositório é 'https://github.com/santos-bruna/bd-2021-2-bec', em vez de 'https://github.com/santos-bruna/bd-2021-2-bec.>' .
COM APROVEITAMENTO.
