### ISSUE TITLE
Tabelas BD Lanches 

### ISSUE THREAD

**Issue by Lari-Rosa** [plinioleitao/bd-2021-2-bec#378]
Contexto: aula de hoje, tratando do Tópico 11a - BD Lanches

Boa noite, professor! 
Durante a aula de hoje o senhor pediu que alguém fizesse novamente a imagem das Tabelas do BD Lanches, corrigindo "coxinha" para "esfirra".

Segue imagem e link para a tabela, caso deseje vê-la.

![image](https://user-images.githubusercontent.com/73893435/151468480-a14435d5-1d49-4abf-94e4-c5bcd1b34963.png)
[https://docs.google.com/spreadsheets/d/1iGK5DaoPXDE-cxOgC5f4Z3hq2AhudyBHe2-dZSVIlYg/edit?usp=sharing](url)

**Comment by plinioleitao** [comment]
Oi Larissa,
Muitíssimo obrigado!
A imagem que você enviou já está disponível no **Tópico 11a**.
Boa tarde.
