### ISSUE TITLE
Tópico <01>

### ISSUE THREAD

**Issue by phablotavares** [plinioleitao/bd-2021-2-bec#396]
Meu registro acadêmico: 201905470
Meu repositório no GitHub: https://github.com/phablotavares/bd-2021-2-bec-

**Comment by plinioleitao** [comment]
Olá Phablo, 
O nome do seu repositório possui o caractere '-' no final, o que difere do solicitado na atividade do Tópico 01.

A resposta à atividade será avaliada como 'sem aproveitamento', pois o prazo da mesma (14/12/2021) já havia expirado quando você postou a resposta (30/01/2022).
