### ISSUE TITLE
[Dúvida] operação de Grouping (ℑ)

### ISSUE THREAD

**Issue by SantosNunes** [plinioleitao/bd-2021-2-bec#451]
Durante a elaboração das respostas da atividade 1 do tópico 12 surgiu uma dúvida, gostaria de saber se é possível fazer uma comparação ao mesmo tempo que um Grouping  ou é obrigatório que haja de uma nova "variável" pra fazer a comparação?
Exemplo:
-A relação MEDIA_SALARIO desta forma ja receberia apenas os valores maiores que 25000?-

MEDIA_SALARIO(Dnum, Media) ← Dnr, (ℑMEDIA Salario  > 25000) (FUNCIONARIO) 

-OU preciso fazer uma seleção para um elemento auxiliar dos valores de MEDIA_SALARIO Media maiores que 25000?-

AUX1← σ Media > 25000 (MEDIA_SALARIO)

**Comment by plinioleitao** [comment]
Olá Marcos Vinícius,

Penso que a resposta a sua pergunta é negativa: "não é possível fazer uma seleção (de grupos) ao mesmo tempo que um agrupamento", mesmo que a sintaxe da linguagem de consulta permita uma única expressão para tal (por exemplo, a SQL).

Vale esclarecer que a Operação SELEÇÃO, tal como aprendemos até então, é dedicada a 'seleção de _tuplas_'. Contudo a sua pergunta (e atividade do tópico) se refere a seleção de grupos (por exemplo, selecionar os grupos com média salarial superior a 25000).

É didático que enxerguemos distintamente a seleção de _tuplas_ e a seleção de grupos. Então, sugiro que a operação de agrupamento ocorra anterior à operação de seleção de grupos.
