### ISSUE TITLE
Tópico <digite aqui o número do tópico>

### ISSUE THREAD

**Issue by gui-de-paula** [plinioleitao/bd-2021-2-bec#637]
**1)** (A) um, um e um.

**2)** SELECT Pnome, Unome, Nome_dependente
FROM FUNCIONARIO AS F LEFT JOIN DEPENDENTE AS D
ON Cpf = Fcpf
WHERE Pnome LIKE '%l%' AND Nome_dependente LIKE '%l%' OR D.Nome_dependente IS NULL;

**Comment by plinioleitao** [comment]
Peço-lhe atenção no título da _issue_.
Favor ver o enunciado e as respostas postadas no Tópico.
SEM APROVEITAMENTO.
