### ISSUE TITLE
Topico 19

### ISSUE THREAD

**Issue by David7810** [plinioleitao/bd-2021-2-bec#764]
1-

SELECT Nome, CodProduto
FROM PRODUTO AS pr
JOIN (SELECT PrecoUnitario
FROM PRODUTO
ORDER BY PrecoUnictario
LIMIT 5) as pl
ON pr.PrecoUnitario = pl.PrecoUnitario

2-

SELECT CodProduto, Nome
FROM produto as pr
WHERE 5 > (SELECT COUNT (DISTINCT PrecoUnitario)
FROM PRODUTO AS pl
WHERE pr.PrecoUnitario > pl.PrecoUnitario)

**Comment by plinioleitao** [comment]
1. A resposta está incorreta, pois o banco de dados pode ter mais de um produto com o mesmo preço.
2. Retornar os produtos mais caros.

SEM APROVEITAMENTO.
